website/models.py
"""All the DB infomation"""
from lib2to3.pgen2.token import STRING
import string
from sqlalchemy.sql import func
from flask_login import UserMixin
from . import db


# database model for notes
class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    about = db.Column(db.String(150))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


# database model for books
class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    author = db.Column(db.String(150))
    rating = db.Column(db.Integer)
    imageLink = db.Column(db.String(500))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


# database model for users
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    books = db.relationship('Book')
    notes = db.relationship('Note')

website/__init__.py
"""TODO"""
from os import path
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

# is tutorialo migrate
from flask_migrate import Migrate


db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    """TODO"""
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret key for an app'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth
    from .models import User, Book, Note

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    create_database(app)
    # is tutorialo migrate
    migrate = Migrate(app, db)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    """TODO"""
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
"""Registration and login"""
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in succesfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up',  methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be greater than 6 characters', category='error')
        else:
            new_user = User(email=email, first_name=first_name,
                            password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
"""Books and notes"""
import json
import requests
from flask import Blueprint, jsonify, render_template, request, flash
from flask_login import login_required, current_user
from .models import Book, Note
from . import db


views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html")


@views.route('/draft', methods=['GET', 'POST'])
@login_required
def draft():
    if request.method == 'POST':
        about = request.form.get('about')
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(about=about, data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("draft.html", user=current_user)


@views.route('/delete-book', methods=['POST'])
def delete_book():
    book = json.loads(request.data)
    book_id = book['bookId']
    book = Book.query.get(book_id)
    if book:
        if book.user_id == current_user.id:
            db.session.delete(book)
            db.session.commit()
    return jsonify({})


@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    note_id = note['noteId']
    note = Note.query.get(note_id)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
    return jsonify({})


@views.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == 'POST':
        # Define a variable with the URL of the API
        name = request.form.get('name')
        author = request.form.get('author')
        api_url = "https://www.googleapis.com/books/v1/volumes?q=" + \
            name + author + "&key=AIzaSyB56VmCX1jXPYWqFj7KDjBSpJRlvOKKjiE"
        # Call the root of the api with GET, store the answer in a response variable
        # This call will return a list of URLs that represent dog pictures
        response = requests.get(api_url)
        # get the result as json
        response_dict = response.json()
        repo_dicts = response_dict['items']
        return render_template("searchResults.html", lenght=len(repo_dicts), repo_dicts=repo_dicts)
    else:
        return render_template("search.html")


@views.route('/searchResults', methods=['GET', 'POST'])
@login_required
def search_results():
    if request.method == 'POST':
        # Then get the data from the form
        google_id = request.form.get('google')
        api_url = "https://www.googleapis.com/books/v1/volumes?q=" + \
            google_id + "&key=AIzaSyB56VmCX1jXPYWqFj7KDjBSpJRlvOKKjiE"
        response = requests.get(api_url)
        response_dict = response.json()
        repo_dicts = response_dict['items']
        repo_dict = repo_dicts[0]
        name = repo_dict['volumeInfo']['title']
        author = repo_dict['volumeInfo']['authors'][0]
        try:
            imageLink = repo_dict['volumeInfo']['imageLinks']['smallThumbnail']
        except:
            imageLink = 'No image'
        book = Book.query.filter_by(name=name).first()
        new_book = Book(name=name, author=author,
                        imageLink=imageLink, user_id=current_user.id)
        db.session.add(new_book)
        db.session.commit()
        flash('Book added!', category='success')
        return render_template("home.html", name=name, author=author, imageLink=imageLink, user=current_user)
    return render_template("search.html")

website/templates/draft.html
{% extends "layout.html" %} {% block title %}Quick notes and book drafts{%
endblock %} {% block content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='styles.css')}}"
/>
<br />
<br />
<h1 align="center" style="color: #363636">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">
    <strong><mark>{{note.about}} </mark></strong>
    <button type="button" class="close" onClick="deleteNote(note.id)">
      <span aria-hidden="true">&times;</span>
    </button>
    <br />
    <em>{{ note.data }}</em>
  </li>
  <br />
  <br />
  <br />
  {% endfor %}
</ul>
<br />
<br />
<br />
<form method="POST">
  <div class="form-group">
    <input
      name="about"
      class="form-control"
      id="about"
      placeholder="Name Of Your Note"
    />
  </div>
  <textarea
    name="note"
    id="note"
    class="form-control"
    placeholder="Your Note"
  ></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form>
{% endblock %}

website/templates/home.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='styles.css')}}"
/>
<!--for typewriting effect-->
<br>
<div style="text-align:center; margin-bottom: 100px;">
<button type ="button"class="btn btn-outline-primary" data-toggle="collapse" href="#collapseExample" role="button" onClick="typeWrite()"> CS50 final: description</button>
</div>

<div class="collapse" id="collapseExample">
<div class="intro">
  <h1 class="typing"></h1>
</div>
</div>
<br>
<br>
<!--the end of tipewriting effect-->
<h1 align="center" style="color:#363636;">Books read by {{current_user.first_name}} </h1>
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Image</th>
      </tr>
    </thead>
    <tbody>
     {% for book in current_user.books %}
     <td>{{book.id}}</td>
     <td>{{book.name}}</td>
     <td>{{book.author}}</td>
     <td><img id="imageLink" src="{{book.imageLink}}" /></td>
        <td><button type="button", class="close" onClick="deleteBook(book.id)">
            <span aria-hidden="true">&times;</span>
        </button>
      </tr>
        {% else %}
            <td></td>
            <tr><td style="color:#363636;"><b>You have no books</b></td></tr>
            <td></td>
        {% endfor %}
    </tbody>
  </table>

{% endblock %}

website/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div clas="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="search" href="/search">Search</a>
          <a class="nav-item nav-link" id="draft" href="/draft">Notes</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <buton type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </buton>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <buton type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </buton>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}{% block content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='styles.css')}}"
/>
<br>
<br>

<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"/>
    </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password"/>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Login</button>
    </div>
</form>
{% endblock %}

website/templates/search.html
{% extends "layout.html" %} {% block title %}Search{% endblock %} {% block
content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='styles.css')}}"
/>
<br />
<br />
<h1 align="center" style="color: #363636">Search your books</h1>

<form method="POST">
  <div class="form-group">
    <label for="title">Title</label>
    <input
      type="text"
      class="form-control"
      id="name"
      name="name"
      placeholder="Enter the title of the book, eg.: Mistborn"
    />
  </div>
  <div class="form-group">
    <label for="author">Author</label>
    <input
      type="text"
      class="form-control"
      id="author"
      name="author"
      placeholder="Enter the author of the book, eg.: Brandon Sanderson"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Search</button>
</form>

{% endblock %}

website/templates/searchResults.html
{% extends "layout.html" %} {% block title %}Search Results{% endblock %} {%
block content %}

<h1 align="center" style="color: rgb(31, 31, 39)">Search Results</h1>
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='styles.css')}}"
/>

<form action="{{url_for('views.search_results')}}" method="POST">
  <div class="container">
    <main class="grid">
      {% for i in range(0, lenght) %}
      <article>
        {% if repo_dicts[i]['volumeInfo']['imageLinks'] %}
        <img
          id="imageLink"
          src="{{ repo_dicts[i]['volumeInfo']['imageLinks']['smallThumbnail']}}"
          alt="Photo"
        />
        {% else %}
        <img
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png"
          alt=""
        />
        {% endif %}
        <div class="text">
          <h3 id="title" name="title">
            {{repo_dicts[i]['volumeInfo']['title']}}
          </h3>
          <p id="authors">
            {% if repo_dicts[i]['volumeInfo']['authors']%}
            {{repo_dicts[i]['volumeInfo']['authors'][0]}} {%endif%}
          </p>
          <button
            type="submit"
            name="google"
            value="{{ repo_dicts[i]['id']}} {{repo_dicts[i]['volumeInfo']['title']}} "
          >
            Add to My Books {{value}}
          </button>
        </div>
      </article>
      {% endfor%}
    </main>
  </div>
</form>

{% endblock %}

website/templates/sign_up.html
{% extends "layout.html" %} {% block title %}Sign UP{% endblock %}{% block
content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='styles.css')}}"
/>

<br />
<br />
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
    <div class="form-group">
      <label for="password1">Password</label>
      <input
        type="password"
        class="form-control"
        id="password1"
        name="password1"
        placeholder="Enter password"
      />
    </div>
    <div class="form-group">
      <label for="password2">Password (Confirm)</label>
      <input
        type="password"
        class="form-control"
        id="password2"
        name="password2"
        placeholder="Confirm password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>
{% endblock %}